-- MySQL Script generated by MySQL Workbench
-- Sat May  6 23:14:26 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema accueil_ferme
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `address` ;

CREATE TABLE IF NOT EXISTS `address` (
  `pk` INT NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(255) NULL,
  `postal_code` VARCHAR(20) NULL,
  `city` VARCHAR(105) NULL,
  `region` VARCHAR(105) NULL,
  `country` VARCHAR(105) NULL,
  PRIMARY KEY (`pk`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `person` ;

CREATE TABLE IF NOT EXISTS `person` (
  `pk` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NULL,
  `firstname` VARCHAR(105) NULL,
  `lastname` VARCHAR(105) NULL,
  `birthday` DATE NULL,
  `phone` VARCHAR(20) NULL,
  `address_pk` INT NULL,
  `comment` TEXT NULL,
  PRIMARY KEY (`pk`),
  INDEX `fk_personne_adresse1_idx` (`address_pk` ASC),
  CONSTRAINT `fk_personne_adresse1`
    FOREIGN KEY (`address_pk`)
    REFERENCES `address` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `event_cat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `event_cat` ;

CREATE TABLE IF NOT EXISTS `event_cat` (
  `pk` INT NOT NULL AUTO_INCREMENT,
  `slug` VARCHAR(45) NULL,
  `name` VARCHAR(255) NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`pk`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `event` ;

CREATE TABLE IF NOT EXISTS `event` (
  `pk` INT NOT NULL AUTO_INCREMENT,
  `slug` VARCHAR(105) NULL,
  `name` VARCHAR(255) NULL,
  `start_date` DATETIME NULL,
  `end_date` DATETIME NULL,
  `description` TEXT NULL,
  `event_cat_pk` INT NOT NULL,
  PRIMARY KEY (`pk`),
  INDEX `fk_event_event_cat1_idx` (`event_cat_pk` ASC),
  CONSTRAINT `fk_event_event_cat1`
    FOREIGN KEY (`event_cat_pk`)
    REFERENCES `event_cat` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `group` ;

CREATE TABLE IF NOT EXISTS `group` (
  `pk` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(105) NULL,
  `adress_pk` INT NULL,
  `comment` TEXT NULL,
  `is_familly` TINYINT(1) NULL,
  `event_pk` INT NULL,
  PRIMARY KEY (`pk`),
  INDEX `fk_famille_adresse1_idx` (`adress_pk` ASC),
  INDEX `fk_group_event1_idx` (`event_pk` ASC),
  CONSTRAINT `fk_famille_adresse1`
    FOREIGN KEY (`adress_pk`)
    REFERENCES `address` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_group_event1`
    FOREIGN KEY (`event_pk`)
    REFERENCES `event` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `group_link`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `group_link` ;

CREATE TABLE IF NOT EXISTS `group_link` (
  `pk` INT NOT NULL AUTO_INCREMENT,
  `slug` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`pk`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `person_has_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `person_has_group` ;

CREATE TABLE IF NOT EXISTS `person_has_group` (
  `person_id` INT NOT NULL,
  `family_id` INT NOT NULL,
  `is_in_family` TINYINT(1) NULL,
  `can_manage` TINYINT(1) NULL,
  `group_link_pk` INT NOT NULL,
  PRIMARY KEY (`person_id`, `family_id`),
  INDEX `fk_personnes_has_famille_famille1_idx` (`family_id` ASC),
  INDEX `fk_personnes_has_famille_personnes_idx` (`person_id` ASC),
  INDEX `fk_personne_has_famille_lien_famille1_idx` (`group_link_pk` ASC),
  CONSTRAINT `fk_personnes_has_famille_personnes`
    FOREIGN KEY (`person_id`)
    REFERENCES `person` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_personnes_has_famille_famille1`
    FOREIGN KEY (`family_id`)
    REFERENCES `group` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_personne_has_famille_lien_famille1`
    FOREIGN KEY (`group_link_pk`)
    REFERENCES `group_link` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `payment` ;

CREATE TABLE IF NOT EXISTS `payment` (
  `pk` INT NOT NULL AUTO_INCREMENT,
  `person_id` INT NOT NULL,
  `date` DATETIME NULL,
  `comment` TEXT NULL,
  PRIMARY KEY (`pk`),
  INDEX `fk_inscription_has_personne_personne1_idx` (`person_id` ASC),
  CONSTRAINT `fk_inscription_has_personne_personne1`
    FOREIGN KEY (`person_id`)
    REFERENCES `person` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `registration_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `registration_type` ;

CREATE TABLE IF NOT EXISTS `registration_type` (
  `pk` INT NOT NULL AUTO_INCREMENT,
  `slug` VARCHAR(45) NULL,
  `name` VARCHAR(255) NULL,
  `description` TEXT NULL,
  `event_id` INT NOT NULL,
  `price` FLOAT NULL,
  PRIMARY KEY (`pk`),
  INDEX `fk_type_inscription_event1_idx` (`event_id` ASC),
  CONSTRAINT `fk_type_inscription_event1`
    FOREIGN KEY (`event_id`)
    REFERENCES `event` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `registration`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `registration` ;

CREATE TABLE IF NOT EXISTS `registration` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `person_id` INT NOT NULL,
  `event_id` INT NOT NULL,
  `arrival_date` DATETIME NULL,
  `departure_date` DATETIME NULL,
  `register_date` DATETIME NULL,
  `update_date` DATETIME NULL,
  `payment_pk` INT NULL,
  `comment` TEXT NULL,
  `registration_type_pk` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_inscription_personne1_idx` (`person_id` ASC),
  INDEX `fk_inscription_event1_idx` (`event_id` ASC),
  INDEX `fk_inscription_paiements1_idx` (`payment_pk` ASC),
  INDEX `fk_inscription_type_inscription1_idx` (`registration_type_pk` ASC),
  CONSTRAINT `fk_inscription_personne1`
    FOREIGN KEY (`person_id`)
    REFERENCES `person` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inscription_event1`
    FOREIGN KEY (`event_id`)
    REFERENCES `event` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inscription_paiements1`
    FOREIGN KEY (`payment_pk`)
    REFERENCES `payment` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inscription_type_inscription1`
    FOREIGN KEY (`registration_type_pk`)
    REFERENCES `registration_type` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `activity_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `activity_role` ;

CREATE TABLE IF NOT EXISTS `activity_role` (
  `pk` INT NOT NULL AUTO_INCREMENT,
  `slug` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`pk`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `place_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `place_type` ;

CREATE TABLE IF NOT EXISTS `place_type` (
  `pk` INT NOT NULL AUTO_INCREMENT,
  `slug` VARCHAR(45) NULL,
  `name` VARCHAR(255) NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`pk`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `place`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `place` ;

CREATE TABLE IF NOT EXISTS `place` (
  `pk` INT NOT NULL AUTO_INCREMENT,
  `slug` VARCHAR(45) NULL,
  `name` VARCHAR(255) NULL,
  `description` TEXT NULL,
  `place_type_pk` INT NOT NULL,
  `parent_pk` INT NOT NULL,
  `address_pk` INT NOT NULL,
  PRIMARY KEY (`pk`),
  INDEX `fk_hebergement_hebergement_type1_idx` (`place_type_pk` ASC),
  INDEX `fk_lieu_lieu1_idx` (`parent_pk` ASC),
  INDEX `fk_lieu_adresse1_idx` (`address_pk` ASC),
  CONSTRAINT `fk_hebergement_hebergement_type1`
    FOREIGN KEY (`place_type_pk`)
    REFERENCES `place_type` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lieu_lieu1`
    FOREIGN KEY (`parent_pk`)
    REFERENCES `place` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lieu_adresse1`
    FOREIGN KEY (`address_pk`)
    REFERENCES `address` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `activity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `activity` ;

CREATE TABLE IF NOT EXISTS `activity` (
  `pk` INT NOT NULL AUTO_INCREMENT,
  `event_id` INT NULL,
  `slug` VARCHAR(105) NULL,
  `nom` VARCHAR(255) NULL,
  `description` TEXT NULL,
  `start_date` DATETIME NULL,
  `end_date` DATETIME NULL,
  `place_pk` INT NOT NULL,
  `is_public` TINYINT(1) NULL,
  `start_age` INT NULL,
  `end_age` INT NULL,
  INDEX `fk_event_has_benevolat_event1_idx` (`event_id` ASC),
  PRIMARY KEY (`pk`),
  INDEX `fk_activite_lieu1_idx` (`place_pk` ASC),
  CONSTRAINT `fk_event_has_benevolat_event1`
    FOREIGN KEY (`event_id`)
    REFERENCES `event` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_activite_lieu1`
    FOREIGN KEY (`place_pk`)
    REFERENCES `place` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `participant_has_activity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `participant_has_activity` ;

CREATE TABLE IF NOT EXISTS `participant_has_activity` (
  `activity_pk` INT NOT NULL,
  `inscription_id` INT NOT NULL,
  `activity_role_pk` INT NOT NULL,
  PRIMARY KEY (`activity_pk`, `inscription_id`),
  INDEX `fk_activite_has_inscription_inscription1_idx` (`inscription_id` ASC),
  INDEX `fk_activite_has_inscription_activite1_idx` (`activity_pk` ASC),
  INDEX `fk_activite_has_participant_activite_role1_idx` (`activity_role_pk` ASC),
  CONSTRAINT `fk_activite_has_inscription_activite1`
    FOREIGN KEY (`activity_pk`)
    REFERENCES `activity` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_activite_has_inscription_inscription1`
    FOREIGN KEY (`inscription_id`)
    REFERENCES `registration` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_activite_has_participant_activite_role1`
    FOREIGN KEY (`activity_role_pk`)
    REFERENCES `activity_role` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tag` ;

CREATE TABLE IF NOT EXISTS `tag` (
  `pk` INT NOT NULL AUTO_INCREMENT,
  `slug` VARCHAR(45) NULL,
  `name` VARCHAR(255) NULL,
  PRIMARY KEY (`pk`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `activity_has_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `activity_has_tag` ;

CREATE TABLE IF NOT EXISTS `activity_has_tag` (
  `activity_pk` INT NOT NULL,
  `activity_tag_pk` INT NOT NULL,
  PRIMARY KEY (`activity_pk`, `activity_tag_pk`),
  INDEX `fk_activite_has_activite_tag_activite_tag1_idx` (`activity_tag_pk` ASC),
  INDEX `fk_activite_has_activite_tag_activite1_idx` (`activity_pk` ASC),
  CONSTRAINT `fk_activite_has_activite_tag_activite1`
    FOREIGN KEY (`activity_pk`)
    REFERENCES `activity` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_activite_has_activite_tag_activite_tag1`
    FOREIGN KEY (`activity_tag_pk`)
    REFERENCES `tag` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inscription_has_night_place`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inscription_has_night_place` ;

CREATE TABLE IF NOT EXISTS `inscription_has_night_place` (
  `inscription_id` INT NOT NULL,
  `place_pk` INT NOT NULL,
  `start_date` DATETIME NULL,
  `end_date` DATETIME NULL,
  PRIMARY KEY (`inscription_id`, `place_pk`),
  INDEX `fk_inscription_has_hebergement_hebergement1_idx` (`place_pk` ASC),
  INDEX `fk_inscription_has_hebergement_inscription1_idx` (`inscription_id` ASC),
  CONSTRAINT `fk_inscription_has_hebergement_inscription1`
    FOREIGN KEY (`inscription_id`)
    REFERENCES `registration` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inscription_has_hebergement_hebergement1`
    FOREIGN KEY (`place_pk`)
    REFERENCES `place` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
